# Builder Stage
FROM node:18

# Environment variable to set the API URL
ENV NEXT_PUBLIC_BACKEND_DEV=http://localhost:8080
ENV NEXT_PUBLIC_BACKEND_PROD=http://localhost:8081

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Build the Next.js application
RUN npm run build